{
 "title": "MLOps Model Monitoring Dashboard (Titanic Example)",
 "time": { "from": "2026-01-07T16:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Requests / time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "prediction_request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Drift Events / time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "drift_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prediction Latency Seconds",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prediction_latency_seconds_bucket{le!=\"+Inf\"}[360d])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success vs Error",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prediction_error_total[365d]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(increase(prediction_request_total[365d])) - sum(increase(prediction_error_total[365d]))",
     "legendFormat": "Success"
    }
   ]
  }
 ]
}